version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/api
    overwrite: yes
hooks:
  BeforeInstall:
    - location: aws/scripts/beforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: aws/scripts/afterInstall.sh
      timeout: 300
      runas: ec2-user
