name: CICD
on:
  push:
    branches:
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: elon-kiosk-backend-bucket
    steps:
      - uses: actions/checkout@v3.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.x'

      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1

      - name: Enable yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Delete development dependencies
        run: yarn install --production

      - name: Create .env
        run: |
          cat << EOF > .env
          ${{ secrets.ENVIRONMENTS }}

      - name: Packaging
        run: |
          tar -cpzvf ./$GITHUB_SHA.tgz *

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: elon-kiosk-backend-bucket
    steps:
      - uses: actions/checkout@v3.0.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./$GITHUB_SHA.tgz s3://$S3_BUCKET/build/$GITHUB_SHA.tgz

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name elon-kiosk \
            --file-exists-behavior OVERWRITE \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name elon-kiosk-codedeploy-be-deployment-group \
            --s3-location bucket=$S3_BUCKET,bundleType=tgz,key=build/$GITHUB_SHA.tgz
